################## Cloudformation RaiseTech 課題 ##################
## Author: Daisaku kato
###################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: RaiseTech EIP

Parameters:
  VPCStack:
    Type: String
    Default: RaiseTech

Resources:
#=============================================
# ElasticIP
#=============================================
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: !Join ["-", [!Ref AWS::StackName, cfn, ec2, 1a]]

#=============================================
# Outputs
#=============================================
Outputs:
  ElasticIP :
    Description: RaiseTech-cfn-ElasticIP
    Value: !GetAtt ElasticIP.AllocationId
    Export:
      Name: !Join ["-", [!Ref VPCStack, eip, ec2, 1a]]
