################## Cloudformation RaiseTech 課題 ##################
## Author: Daisaku kato
###################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: RaiseTech EIP

Parameters:
  VPCStack:
    Type: String
    Default: RaiseTech

Resources:
#=============================================
# ElasticIP
#=============================================
  ElasticIP1a:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: !Join ["-", [!Ref AWS::StackName, cfn, ec2, 1a]]

  # ElasticIP1c:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #     - Key: Name
  #       Value: !Join ["-", [!Ref AWS::StackName, cfn, ec2, 1c]]

#=============================================
# Outputs
#=============================================
Outputs:
  ElasticIP1a :
    Description: RaiseTech-cfn-ElasticIP-1a
    Value: !GetAtt ElasticIP1a.AllocationId
    Export:
      Name: !Join ["-", [!Ref VPCStack, eip, ec2, 1a]]

  # ElasticIP1c :
  #   Description: RaiseTech-cfn-ElasticIP-1c
  #   Value: !GetAtt ElasticIP1c.AllocationId
  #   Export:
  #     Name: !Join ["-", [!Ref VPCStack, eip, ec2, 1c]]
